# Generated by Django 5.2.10 on 2026-03-13 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0086_flip_steamid_steam_account_id"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tournament_name", models.CharField(max_length=255)),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("single_elimination", "Single Elimination"),
                            ("double_elimination", "Double Elimination"),
                            ("swiss", "Swiss Bracket"),
                        ],
                        default="double_elimination",
                        max_length=30,
                    ),
                ),
                (
                    "game_type",
                    models.IntegerField(
                        choices=[(1, "Dota 2"), (2, "Deadlock")], default=1
                    ),
                ),
                (
                    "draft_type",
                    models.CharField(
                        choices=[
                            ("snake", "Snake"),
                            ("normal", "Normal"),
                            ("shuffle", "Shuffle"),
                        ],
                        default="shuffle",
                        max_length=10,
                    ),
                ),
                ("people_per_team", models.IntegerField(default=5)),
                ("number_of_teams", models.IntegerField(default=2)),
                ("tournament_date", models.DateTimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(default="America/New_York", max_length=50),
                ),
                ("min_players", models.IntegerField(blank=True, null=True)),
                ("max_players", models.IntegerField(blank=True, null=True)),
                ("signup_deadline_hours", models.IntegerField(blank=True, null=True)),
                ("allow_team_signups", models.BooleanField(default=False)),
                ("allow_user_signups", models.BooleanField(default=True)),
                ("auto_approve", models.BooleanField(default=False)),
                ("auto_confirm", models.BooleanField(default=False)),
                ("require_mmr_verified", models.BooleanField(default=False)),
                ("require_steam_id", models.BooleanField(default=False)),
                ("require_profile_complete", models.BooleanField(default=False)),
                ("roll_call_enabled", models.BooleanField(default=False)),
                (
                    "roll_call_mode",
                    models.CharField(
                        choices=[("manual", "Manual")], default="manual", max_length=20
                    ),
                ),
                ("auto_start", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("scheduled_at", models.DateTimeField()),
                ("signups_open_at", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("signups_open", "Signups Open"),
                            ("roll_call", "Roll Call"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_repeater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="events.eventrepeater",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="app.organization",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_event",
                        to="app.tournament",
                    ),
                ),
                (
                    "tournament_league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="app.league",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "scheduled_at"],
                        name="events_even_state_48c345_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("event_repeater__isnull", False)),
                        fields=("event_repeater", "scheduled_at"),
                        name="unique_repeater_scheduled_at",
                    )
                ],
            },
        ),
    ]
