# Generated by Django 5.2.10 on 2026-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_eventteam_eventsignup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="number_of_teams",
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name="eventrepeater",
            name="number_of_teams",
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
