# Generated by Django 5.2.10 on 2026-03-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_number_of_teams_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="discord_confirm_attendance",
            field=models.BooleanField(
                default=False,
                help_text="Require attendance confirmation via Discord message reply on event day",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_create_event",
            field=models.BooleanField(
                default=False, help_text="Create a Discord scheduled event"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_event_description",
            field=models.TextField(
                blank=True, default="", help_text="Custom description for Discord event"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_event_info",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional info shown in the Discord event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_event_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom title for Discord event (blank = use event name)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_profile_reminder",
            field=models.BooleanField(
                default=False,
                help_text="Remind users to complete their profile before the event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_signup_reminder",
            field=models.BooleanField(
                default=False, help_text="Send a signup reminder before the event"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_signup_reminder_hours",
            field=models.IntegerField(
                default=24, help_text="Hours before event to send signup reminder"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_sync_signups",
            field=models.BooleanField(
                default=False, help_text="Sync signups to the Discord event"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_confirm_attendance",
            field=models.BooleanField(
                default=False,
                help_text="Require attendance confirmation via Discord message reply on event day",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_create_event",
            field=models.BooleanField(
                default=False, help_text="Create a Discord scheduled event"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_event_description",
            field=models.TextField(
                blank=True, default="", help_text="Custom description for Discord event"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_event_info",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional info shown in the Discord event",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_event_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom title for Discord event (blank = use event name)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_notify_new_events",
            field=models.BooleanField(
                default=False,
                help_text="Notify users when new events are generated and ready for signup",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_profile_reminder",
            field=models.BooleanField(
                default=False,
                help_text="Remind users to complete their profile before the event",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_signup_reminder",
            field=models.BooleanField(
                default=False, help_text="Send a signup reminder before the event"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_signup_reminder_hours",
            field=models.IntegerField(
                default=24, help_text="Hours before event to send signup reminder"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_sync_signups",
            field=models.BooleanField(
                default=False, help_text="Sync signups to the Discord event"
            ),
        ),
    ]
