# Generated by Django 5.2.10 on 2026-03-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_discord_confirm_attendance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="discord_announcement",
            field=models.BooleanField(
                default=False, help_text="Post a pre-day announcement in a channel"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_announcement_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord channel ID for pre-day announcement",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_announcement_hours",
            field=models.IntegerField(
                default=24, help_text="Hours before event to post announcement"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_mark_interested",
            field=models.BooleanField(
                default=False,
                help_text="Mark signups as 'interested' on the Discord scheduled event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_post_signups",
            field=models.BooleanField(
                default=False,
                help_text="Post an event embed to a channel for reaction-based signups",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_post_signups_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord channel ID to post signup embed in",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_announcement",
            field=models.BooleanField(
                default=False, help_text="Post a pre-day announcement in a channel"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_announcement_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord channel ID for pre-day announcement",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_announcement_hours",
            field=models.IntegerField(
                default=24, help_text="Hours before event to post announcement"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_mark_interested",
            field=models.BooleanField(
                default=False,
                help_text="Mark signups as 'interested' on the Discord scheduled event",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_post_signups",
            field=models.BooleanField(
                default=False,
                help_text="Post an event embed to a channel for reaction-based signups",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_post_signups_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord channel ID to post signup embed in",
                max_length=20,
            ),
        ),
    ]
