# Generated by Django 5.2.10 on 2026-03-15 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_discord_announcement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="discord_announcement_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord channel ID for pre-day announcement",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(\\d{17,20})?$", "Must be a valid Discord snowflake ID"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="discord_post_signups_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord channel ID to post signup embed in",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(\\d{17,20})?$", "Must be a valid Discord snowflake ID"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="eventrepeater",
            name="discord_announcement_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord channel ID for pre-day announcement",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(\\d{17,20})?$", "Must be a valid Discord snowflake ID"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="eventrepeater",
            name="discord_post_signups_channel_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Discord channel ID to post signup embed in",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(\\d{17,20})?$", "Must be a valid Discord snowflake ID"
                    )
                ],
            ),
        ),
    ]
