# Generated by Django 5.2.10 on 2026-03-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_discord_announcement_channel_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="auto_start",
        ),
        migrations.RemoveField(
            model_name="eventrepeater",
            name="auto_start",
        ),
        migrations.AddField(
            model_name="event",
            name="captains_draft_time",
            field=models.IntegerField(
                default=10, help_text="Seconds per draft pick in Captain's Mode"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="custom_game_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom game/lobby name (for custom game mode)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="game_mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("captains_mode", "Captain's Mode"),
                    ("turbo", "Turbo"),
                    ("custom", "Custom Lobby"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="lobby_steam_league_id",
            field=models.IntegerField(
                blank=True,
                help_text="Steam league ID for Dota 2 lobby ticket",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="captains_draft_time",
            field=models.IntegerField(
                default=10, help_text="Seconds per draft pick in Captain's Mode"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="custom_game_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom game/lobby name (for custom game mode)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="game_mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("captains_mode", "Captain's Mode"),
                    ("turbo", "Turbo"),
                    ("custom", "Custom Lobby"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="lobby_steam_league_id",
            field=models.IntegerField(
                blank=True,
                help_text="Steam league ID for Dota 2 lobby ticket",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="eventrepeater",
            name="discord_notify_new_events",
            field=models.BooleanField(
                default=True,
                help_text="Notify users when new events are generated and ready for signup",
            ),
        ),
    ]
