# Generated by Django 5.2.10 on 2026-03-15 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_remove_event_auto_start_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="discord_confirm_attendance_hours",
            field=models.IntegerField(
                default=2,
                help_text="Hours before event to send attendance confirmation request",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_profile_reminder_hours",
            field=models.IntegerField(
                default=24,
                help_text="Hours before event to send profile update reminder",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_confirm_attendance_hours",
            field=models.IntegerField(
                default=2,
                help_text="Hours before event to send attendance confirmation request",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_profile_reminder_hours",
            field=models.IntegerField(
                default=24,
                help_text="Hours before event to send profile update reminder",
            ),
        ),
        migrations.CreateModel(
            name="RepeaterSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event_repeater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="events.eventrepeater",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repeater_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event_repeater", "user"),
                        name="unique_repeater_user_subscription",
                    )
                ],
            },
        ),
    ]
