# Generated by Django 5.2.10 on 2026-03-15 16:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0088_tournament_captains_draft_time_and_more"),
        ("events", "0009_event_discord_confirm_attendance_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tournament_league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="app.league",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="tournament_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="eventrepeater",
            name="tournament_league",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="app.league",
            ),
        ),
        migrations.AlterField(
            model_name="eventrepeater",
            name="tournament_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="OrgEventDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tournament_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tournament_type",
                    models.CharField(
                        choices=[
                            ("single_elimination", "Single Elimination"),
                            ("double_elimination", "Double Elimination"),
                            ("swiss", "Swiss Bracket"),
                        ],
                        default="double_elimination",
                        max_length=30,
                    ),
                ),
                (
                    "game_type",
                    models.IntegerField(
                        choices=[(1, "Dota 2"), (2, "Deadlock")], default=1
                    ),
                ),
                (
                    "draft_type",
                    models.CharField(
                        choices=[
                            ("snake", "Snake"),
                            ("normal", "Normal"),
                            ("shuffle", "Shuffle"),
                        ],
                        default="shuffle",
                        max_length=10,
                    ),
                ),
                ("people_per_team", models.IntegerField(default=5)),
                (
                    "number_of_teams",
                    models.IntegerField(blank=True, default=2, null=True),
                ),
                ("tournament_date", models.DateTimeField(blank=True, null=True)),
                (
                    "game_mode",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("captains_mode", "Captain's Mode"),
                            ("turbo", "Turbo"),
                            ("custom", "Custom Lobby"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "custom_game_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom game/lobby name (for custom game mode)",
                        max_length=255,
                    ),
                ),
                (
                    "captains_draft_time",
                    models.IntegerField(
                        default=10, help_text="Seconds per draft pick in Captain's Mode"
                    ),
                ),
                (
                    "lobby_steam_league_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Steam league ID for Dota 2 lobby ticket",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="America/New_York", max_length=50),
                ),
                ("min_players", models.IntegerField(blank=True, null=True)),
                ("max_players", models.IntegerField(blank=True, null=True)),
                ("signup_deadline_hours", models.IntegerField(blank=True, null=True)),
                ("allow_team_signups", models.BooleanField(default=False)),
                ("allow_user_signups", models.BooleanField(default=True)),
                ("auto_approve", models.BooleanField(default=False)),
                ("auto_confirm", models.BooleanField(default=False)),
                ("require_mmr_verified", models.BooleanField(default=False)),
                ("require_steam_id", models.BooleanField(default=False)),
                ("require_profile_complete", models.BooleanField(default=False)),
                ("roll_call_enabled", models.BooleanField(default=False)),
                (
                    "roll_call_mode",
                    models.CharField(
                        choices=[("manual", "Manual")], default="manual", max_length=20
                    ),
                ),
                (
                    "discord_create_event",
                    models.BooleanField(
                        default=False, help_text="Create a Discord scheduled event"
                    ),
                ),
                (
                    "discord_sync_signups",
                    models.BooleanField(
                        default=False, help_text="Sync signups to the Discord event"
                    ),
                ),
                (
                    "discord_event_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom title for Discord event (blank = use event name)",
                        max_length=255,
                    ),
                ),
                (
                    "discord_event_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Custom description for Discord event",
                    ),
                ),
                (
                    "discord_event_info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional info shown in the Discord event",
                    ),
                ),
                (
                    "discord_signup_reminder",
                    models.BooleanField(
                        default=False,
                        help_text="Send a signup reminder before the event",
                    ),
                ),
                (
                    "discord_signup_reminder_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Hours before event to send signup reminder",
                    ),
                ),
                (
                    "discord_confirm_attendance",
                    models.BooleanField(
                        default=False,
                        help_text="Require attendance confirmation via Discord message reply on event day",
                    ),
                ),
                (
                    "discord_confirm_attendance_hours",
                    models.IntegerField(
                        default=2,
                        help_text="Hours before event to send attendance confirmation request",
                    ),
                ),
                (
                    "discord_profile_reminder",
                    models.BooleanField(
                        default=False,
                        help_text="Remind users to complete their profile before the event",
                    ),
                ),
                (
                    "discord_profile_reminder_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Hours before event to send profile update reminder",
                    ),
                ),
                (
                    "discord_mark_interested",
                    models.BooleanField(
                        default=False,
                        help_text="Mark signups as 'interested' on the Discord scheduled event",
                    ),
                ),
                (
                    "discord_post_signups",
                    models.BooleanField(
                        default=False,
                        help_text="Post an event embed to a channel for reaction-based signups",
                    ),
                ),
                (
                    "discord_post_signups_channel_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Discord channel ID to post signup embed in",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(\\d{17,20})?$",
                                "Must be a valid Discord snowflake ID",
                            )
                        ],
                    ),
                ),
                (
                    "discord_announcement",
                    models.BooleanField(
                        default=False,
                        help_text="Post a pre-day announcement in a channel",
                    ),
                ),
                (
                    "discord_announcement_channel_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Discord channel ID for pre-day announcement",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^(\\d{17,20})?$",
                                "Must be a valid Discord snowflake ID",
                            )
                        ],
                    ),
                ),
                (
                    "discord_announcement_hours",
                    models.IntegerField(
                        default=24, help_text="Hours before event to post announcement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_defaults",
                        to="app.organization",
                    ),
                ),
                (
                    "tournament_league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="app.league",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Org event defaults",
            },
        ),
    ]
