# Generated by Django 5.2.10 on 2026-03-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_event_tournament_league_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="discord_announcement_role_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Discord role IDs to @ mention in the announcement",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_signup_role_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Discord role IDs to @ mention in the signup post",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_announcement_role_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Discord role IDs to @ mention in the announcement",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_signup_role_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Discord role IDs to @ mention in the signup post",
            ),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="discord_announcement_role_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Discord role IDs to @ mention in the announcement",
            ),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="discord_signup_role_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of Discord role IDs to @ mention in the signup post",
            ),
        ),
        migrations.AlterField(
            model_name="eventsignup",
            name="status",
            field=models.CharField(
                choices=[
                    ("rsvp", "RSVP"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("confirmed", "Confirmed"),
                    ("waitlisted", "Waitlisted"),
                    ("tentative", "Tentative"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="rsvp",
                max_length=20,
            ),
        ),
    ]
