# Generated by Django 5.2.10 on 2026-03-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_add_discord_role_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="discord_require_battlecup_screenshot",
            field=models.BooleanField(
                default=False,
                help_text="Require never-ranked players to upload battle cup ticket screenshot",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_require_rank_screenshot",
            field=models.BooleanField(
                default=False,
                help_text="Require active ranked players to upload MMR screenshot",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="min_mmr",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum MMR required for event approval (null = no minimum)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_require_battlecup_screenshot",
            field=models.BooleanField(
                default=False,
                help_text="Require never-ranked players to upload battle cup ticket screenshot",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_require_rank_screenshot",
            field=models.BooleanField(
                default=False,
                help_text="Require active ranked players to upload MMR screenshot",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="min_mmr",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum MMR required for event approval (null = no minimum)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="discord_require_battlecup_screenshot",
            field=models.BooleanField(
                default=False,
                help_text="Require never-ranked players to upload battle cup ticket screenshot",
            ),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="discord_require_rank_screenshot",
            field=models.BooleanField(
                default=False,
                help_text="Require active ranked players to upload MMR screenshot",
            ),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="min_mmr",
            field=models.IntegerField(
                blank=True,
                help_text="Minimum MMR required for event approval (null = no minimum)",
                null=True,
            ),
        ),
    ]
