# Generated by Django 5.2.10 on 2026-03-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_event_discord_require_battlecup_screenshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_active_mmr",
            field=models.BooleanField(
                default=True, help_text="Allow players with active MMR to sign up"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="allow_battlecup_rating",
            field=models.BooleanField(
                default=True,
                help_text="Allow never-ranked players (battle cup tier) to sign up",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="allow_previous_rank",
            field=models.BooleanField(
                default=True,
                help_text="Allow players with previous (expired) rank to sign up",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="allow_active_mmr",
            field=models.BooleanField(
                default=True, help_text="Allow players with active MMR to sign up"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="allow_battlecup_rating",
            field=models.BooleanField(
                default=True,
                help_text="Allow never-ranked players (battle cup tier) to sign up",
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="allow_previous_rank",
            field=models.BooleanField(
                default=True,
                help_text="Allow players with previous (expired) rank to sign up",
            ),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="allow_active_mmr",
            field=models.BooleanField(
                default=True, help_text="Allow players with active MMR to sign up"
            ),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="allow_battlecup_rating",
            field=models.BooleanField(
                default=True,
                help_text="Allow never-ranked players (battle cup tier) to sign up",
            ),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="allow_previous_rank",
            field=models.BooleanField(
                default=True,
                help_text="Allow players with previous (expired) rank to sign up",
            ),
        ),
    ]
