# Generated by Django 5.2.10 on 2026-03-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_event_allow_active_mmr_event_allow_battlecup_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="discord_subscriber_dm",
            field=models.BooleanField(
                default=False, help_text="Send DM to subscribers before event starts"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_subscriber_dm_hours",
            field=models.IntegerField(
                default=24, help_text="Hours before event to send subscriber DM"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_subscriber_dm",
            field=models.BooleanField(
                default=False, help_text="Send DM to subscribers before event starts"
            ),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_subscriber_dm_hours",
            field=models.IntegerField(
                default=24, help_text="Hours before event to send subscriber DM"
            ),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="discord_subscriber_dm",
            field=models.BooleanField(
                default=False, help_text="Send DM to subscribers before event starts"
            ),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="discord_subscriber_dm_hours",
            field=models.IntegerField(
                default=24, help_text="Hours before event to send subscriber DM"
            ),
        ),
    ]
