# Generated by Django 5.2.10 on 2026-03-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_event_discord_subscriber_dm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="auto_create_hero_drafts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_send_draft_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="discord_send_herodraft_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="auto_create_hero_drafts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_send_draft_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventrepeater",
            name="discord_send_herodraft_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="auto_create_hero_drafts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="discord_send_draft_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orgeventdefaults",
            name="discord_send_herodraft_link",
            field=models.BooleanField(default=False),
        ),
    ]
