# Generated by Django 5.2.10 on 2026-03-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_event_auto_create_hero_drafts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="discord_signup_reminder",
            field=models.BooleanField(
                default=True,
                help_text="DM subscribers who haven't signed up before the event",
            ),
        ),
        migrations.AlterField(
            model_name="eventrepeater",
            name="discord_signup_reminder",
            field=models.BooleanField(
                default=True,
                help_text="DM subscribers who haven't signed up before the event",
            ),
        ),
        migrations.AlterField(
            model_name="orgeventdefaults",
            name="discord_signup_reminder",
            field=models.BooleanField(
                default=True,
                help_text="DM subscribers who haven't signed up before the event",
            ),
        ),
    ]
