# Generated by Django 5.2.10 on 2026-03-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_signup_reminder_default_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="discord_send_draft_link",
            field=models.BooleanField(
                default=True,
                help_text="DM participants the draft link when the team draft starts",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="discord_send_herodraft_link",
            field=models.BooleanField(
                default=True,
                help_text="DM participants the hero draft link when a hero draft starts",
            ),
        ),
        migrations.AlterField(
            model_name="eventrepeater",
            name="discord_send_draft_link",
            field=models.BooleanField(
                default=True,
                help_text="DM participants the draft link when the team draft starts",
            ),
        ),
        migrations.AlterField(
            model_name="eventrepeater",
            name="discord_send_herodraft_link",
            field=models.BooleanField(
                default=True,
                help_text="DM participants the hero draft link when a hero draft starts",
            ),
        ),
        migrations.AlterField(
            model_name="orgeventdefaults",
            name="discord_send_draft_link",
            field=models.BooleanField(
                default=True,
                help_text="DM participants the draft link when the team draft starts",
            ),
        ),
        migrations.AlterField(
            model_name="orgeventdefaults",
            name="discord_send_herodraft_link",
            field=models.BooleanField(
                default=True,
                help_text="DM participants the hero draft link when a hero draft starts",
            ),
        ),
    ]
