# Generated by Django 5.2.10 on 2026-05-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_draft_dm_defaults_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='discord_subscriber_dm',
        ),
        migrations.RemoveField(
            model_name='event',
            name='discord_subscriber_dm_hours',
        ),
        migrations.RemoveField(
            model_name='eventrepeater',
            name='discord_subscriber_dm',
        ),
        migrations.RemoveField(
            model_name='eventrepeater',
            name='discord_subscriber_dm_hours',
        ),
        migrations.RemoveField(
            model_name='orgeventdefaults',
            name='discord_subscriber_dm',
        ),
        migrations.RemoveField(
            model_name='orgeventdefaults',
            name='discord_subscriber_dm_hours',
        ),
    ]
