# Generated by Django 5.2.10 on 2026-08-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_remove_subscriber_dm_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_off_schedule",
            field=models.BooleanField(
                default=False,
                help_text="Attached to a series but not generated by its schedule; excluded from realign and from the series config cascade.",
            ),
        ),
    ]
