# Generated by Django 5.2.10 on 2026-05-19 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # Pin the historical `app` graph so MigratorTestCase tests can resolve
        # PositionsModel (which CustomUser.positions points at, NOT NULL).
        # Without this, migrating to user.0001_initial picks an `app` graph
        # version that may pre-date PositionsModel and breaks setup of any
        # migration test that needs to create a CustomUser at this point.
        ("app", "0094_alter_league_steam_league_id"),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(blank=True, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base User Profile',
            },
        ),
    ]
