# Generated by Django 5.2.10 on 2026-06-07 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0095_remove_customuser_avatar_remove_customuser_nickname"),
        ("user", "0002_backfill_base_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadlockUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.CharField(blank=True, max_length=64, null=True)),
                ("rank_date", models.DateField(blank=True, null=True)),
                (
                    "base_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlock_user_profile",
                        to="user.baseuserprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deadlock User Profile",
            },
        ),
        migrations.CreateModel(
            name="DotaUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_active_dota_mmr", models.BooleanField(default=False)),
                ("dota_mmr_last_verified", models.DateTimeField(blank=True, null=True)),
                (
                    "base_profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dota_user_profile",
                        to="user.baseuserprofile",
                    ),
                ),
                (
                    "positions",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.positionsmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dota User Profile",
            },
        ),
    ]
