# Generated by Django 5.2.10 on 2026-03-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0002_populate_org_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerDeadlockProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unverified_steam_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Steam Friend ID entered via Discord (unverified)",
                        max_length=20,
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Self-reported rank (loose string)",
                        max_length=100,
                    ),
                ),
                (
                    "rank_date",
                    models.DateField(
                        blank=True, help_text="When user last played ranked", null=True
                    ),
                ),
                (
                    "org_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlock_profile",
                        to="org.orguser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Deadlock Profile",
            },
        ),
        migrations.CreateModel(
            name="PlayerDotaProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unverified_steam_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Steam Friend ID entered via Discord (unverified)",
                        max_length=20,
                    ),
                ),
                (
                    "rank_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("previous", "Previously Ranked"),
                            ("never", "Never Ranked"),
                        ],
                        default="never",
                        max_length=10,
                    ),
                ),
                (
                    "rank_medal",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Medal tier (Herald, Guardian, Crusader, Archon, Legend, Ancient, Divine, Immortal)",
                        max_length=50,
                    ),
                ),
                (
                    "rank_date",
                    models.DateField(
                        blank=True,
                        help_text="When user last held this rank (for 'previous' status)",
                        null=True,
                    ),
                ),
                (
                    "battle_cup_tier",
                    models.IntegerField(
                        blank=True,
                        help_text="Max battle cup ticket tier (for 'never' ranked users)",
                        null=True,
                    ),
                ),
                ("pos_1", models.BooleanField(default=False, help_text="Carry")),
                ("pos_2", models.BooleanField(default=False, help_text="Mid")),
                ("pos_3", models.BooleanField(default=False, help_text="Offlane")),
                ("pos_4", models.BooleanField(default=False, help_text="Soft Support")),
                ("pos_5", models.BooleanField(default=False, help_text="Hard Support")),
                (
                    "org_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dota_profile",
                        to="org.orguser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Player Dota Profile",
            },
        ),
    ]
