# Generated by Django 5.2.10 on 2026-03-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0003_playerdeadlockprofile_playerdotaprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerdotaprofile",
            name="battlecup_screenshot",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to uploaded battle cup ticket screenshot",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="playerdotaprofile",
            name="mmr",
            field=models.IntegerField(
                blank=True, help_text="Self-reported numeric MMR", null=True
            ),
        ),
        migrations.AddField(
            model_name="playerdotaprofile",
            name="rank_screenshot",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to uploaded MMR screenshot",
                max_length=500,
            ),
        ),
    ]
