# Generated by Django 5.2.10 on 2026-03-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0005_rename_unverified_steam_id_to_friend_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerdeadlockprofile",
            name="unverified_friend_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Dota 2 Friend ID (self-reported, unverified)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="playerdotaprofile",
            name="unverified_friend_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Dota 2 Friend ID (self-reported, unverified)",
                max_length=20,
            ),
        ),
    ]
