/**
 * CSV Import Smoke Tests
 *
 * Tests the CSV import modal on the organization page using
 * pre-populated test users and CSV fixture files.
 *
 * CSV fixtures are generated by: populate_csv_import_users()
 * Located at: tests/playwright/fixtures/csv/
 *
 * Test users (exist in DB, NOT in any org):
 * - csv_steam_user (pk=1040, steam=76561198800000001)
 * - csv_discord_user (pk=1041, discord=300000000000000001)
 * - csv_both_ids (pk=1042, steam+discord)
 * - csv_conflict_user (pk=1043, steam+discord mismatch)
 * - csv_team_user (pk=1044, steam=76561198800000005)
 */

import {
  test,
  expect,
  visitAndWaitForHydration,
  getFirstLeague,
} from '../../fixtures';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const API_URL = 'https://localhost/api';
const CSV_DIR = path.resolve(__dirname, '../../fixtures/csv');

let orgPk: number;

test.describe('CSV Import - Org', () => {
  test.beforeAll(async ({ browser }) => {
    const context = await browser.newContext({ ignoreHTTPSErrors: true });

    const league = await getFirstLeague(context);
    if (!league) throw new Error('No leagues found. Run just db::populate::all');

    const leagueResp = await context.request.get(`${API_URL}/leagues/${league.pk}/`);
    const leagueData = await leagueResp.json();
    orgPk = typeof leagueData.organization === 'object'
      ? leagueData.organization.pk
      : leagueData.organization;

    await context.close();
  });

  test.beforeEach(async ({ loginAdmin }) => {
    await loginAdmin();
  });

  test('import button visible for admin', async ({ page }) => {
    await visitAndWaitForHydration(page, `/organizations/${orgPk}/?tab=users`);
    await expect(page.getByTestId('org-csv-import-btn')).toBeVisible({ timeout: 10000 });
  });

  test('opens modal and shows drag area', async ({ page }) => {
    await visitAndWaitForHydration(page, `/organizations/${orgPk}/?tab=users`);
    await page.getByTestId('org-csv-import-btn').click();
    await expect(page.getByRole('heading', { name: 'Import CSV' })).toBeVisible();
    await expect(page.getByText('Drop a CSV file here')).toBeVisible();
  });

  test('imports valid CSV with known test users', async ({ page }) => {
    await visitAndWaitForHydration(page, `/organizations/${orgPk}/?tab=users`);
    await page.getByTestId('org-csv-import-btn').click();

    // Upload the valid-import.csv fixture (3 known test users)
    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByText('Drop a CSV file here').click();
    const fileChooser = await fileChooserPromise;
    await fileChooser.setFiles(path.join(CSV_DIR, 'valid-import.csv'));

    // Preview should show 3 valid rows
    await expect(page.getByText('3 valid')).toBeVisible({ timeout: 5000 });

    // Import
    await page.getByRole('button', { name: /Import 3 row/ }).click();

    // Results summary
    await expect(page.getByText('Added')).toBeVisible({ timeout: 10000 });
  });

  test('shows validation errors for bad rows', async ({ page }) => {
    await visitAndWaitForHydration(page, `/organizations/${orgPk}/?tab=users`);
    await page.getByTestId('org-csv-import-btn').click();

    // Upload the errors-import.csv fixture (2 valid + 2 errors)
    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByText('Drop a CSV file here').click();
    const fileChooser = await fileChooserPromise;
    await fileChooser.setFiles(path.join(CSV_DIR, 'errors-import.csv'));

    // Should show both valid and error counts
    await expect(page.getByText('2 valid')).toBeVisible({ timeout: 5000 });
    await expect(page.getByText('2 errors')).toBeVisible({ timeout: 5000 });
  });

  test('creates stub users for unknown Steam IDs', async ({ page }) => {
    await visitAndWaitForHydration(page, `/organizations/${orgPk}/?tab=users`);
    await page.getByTestId('org-csv-import-btn').click();

    // Upload stubs-import.csv (3 unknown Steam IDs → creates stubs)
    const fileChooserPromise = page.waitForEvent('filechooser');
    await page.getByText('Drop a CSV file here').click();
    const fileChooser = await fileChooserPromise;
    await fileChooser.setFiles(path.join(CSV_DIR, 'stubs-import.csv'));

    await expect(page.getByText('3 valid')).toBeVisible({ timeout: 5000 });
    await page.getByRole('button', { name: /Import 3 row/ }).click();

    // All 3 should be added with stubs created
    await expect(page.getByText('Added')).toBeVisible({ timeout: 10000 });
  });
});
