# Generated by Django 5.2 on 2025-08-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0029_remove_tournamentmatch_tournament_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentBracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_rounds",
                    models.PositiveIntegerField(blank=True, default=4, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("single_elimination", "Single Elimination"),
                            ("double_elimination", "Double Elimination"),
                            ("swiss", "Swiss Bracket"),
                        ],
                        default="double_elimination",
                        max_length=20,
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brackets",
                        to="app.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tournament Brackets",
            },
        ),
        migrations.CreateModel(
            name="BracketSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_rounds", models.PositiveIntegerField()),
                ("is_losers_bracket", models.BooleanField(default=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="app.game",
                    ),
                ),
                (
                    "losers_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="losers_slot",
                        to="bracket.bracketslot",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_slots",
                        to="app.team",
                    ),
                ),
                (
                    "winners_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="winners_slot",
                        to="bracket.bracketslot",
                    ),
                ),
                (
                    "bracket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="bracket.tournamentbracket",
                    ),
                ),
            ],
        ),
    ]
