# Generated by Django 5.2 on 2025-08-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bracket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bracketslot",
            name="bracket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="bracket.tournamentbracket",
            ),
        ),
        migrations.AlterField(
            model_name="bracketslot",
            name="losers_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="losers_slot",
                to="bracket.bracketslot",
            ),
        ),
        migrations.AlterField(
            model_name="bracketslot",
            name="winners_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winners_slot",
                to="bracket.bracketslot",
            ),
        ),
    ]
