# Generated by Django 5.2.10 on 2026-03-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=64)),
                ("embed_data", models.JSONField()),
                (
                    "discord_message_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("source", models.CharField(default="unknown", max_length=64)),
                ("source_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "source_id"],
                        name="discordbot__source_6957c4_idx",
                    )
                ],
            },
        ),
    ]
