# Generated by Django 5.2.10 on 2026-03-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordbot", "0002_discordmessagelog"),
        ("events", "0011_add_discord_role_ids"),
        ("org", "0003_playerdeadlockprofile_playerdotaprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guild_id", models.CharField(max_length=64)),
                (
                    "scheduled_event_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_event",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Event",
                "verbose_name_plural": "Discord Events",
            },
        ),
        migrations.CreateModel(
            name="DiscordEventDM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dm_type",
                    models.IntegerField(
                        choices=[
                            (1, "Signup Reminder"),
                            (2, "Profile Update Required"),
                            (3, "Attendance Confirmation"),
                            (4, "Team Draft Started"),
                            (5, "Hero Draft Started"),
                            (6, "Tournament Update"),
                            (7, "Event Cancelled"),
                        ]
                    ),
                ),
                ("message_id", models.CharField(blank=True, max_length=64, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered", models.BooleanField(default=False)),
                ("responded", models.BooleanField(default=False)),
                ("response_text", models.TextField(blank=True, default="")),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discord_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dms",
                        to="discordbot.discordevent",
                    ),
                ),
                (
                    "org_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_event_dms",
                        to="org.orguser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Event DM",
                "verbose_name_plural": "Discord Event DMs",
            },
        ),
        migrations.CreateModel(
            name="DiscordEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("message_id", models.CharField(blank=True, max_length=64, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("success", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "discord_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="discordbot.discordevent",
                    ),
                ),
                (
                    "dm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="discordbot.discordeventdm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Event Log",
                "verbose_name_plural": "Discord Event Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscordEventMsgAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=64)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("forum", "Forum"),
                            ("announcement", "Announcement"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("message_id", models.CharField(blank=True, max_length=64, null=True)),
                ("thread_id", models.CharField(blank=True, max_length=64, null=True)),
                ("has_posted", models.BooleanField(default=False)),
                ("message_last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Event Announcement Message",
                "verbose_name_plural": "Discord Event Announcement Messages",
            },
        ),
        migrations.AddField(
            model_name="discordevent",
            name="announcement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discord_event",
                to="discordbot.discordeventmsgannouncement",
            ),
        ),
        migrations.CreateModel(
            name="DiscordEventMsgSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=64)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("forum", "Forum"),
                            ("announcement", "Announcement"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("message_id", models.CharField(blank=True, max_length=64, null=True)),
                ("thread_id", models.CharField(blank=True, max_length=64, null=True)),
                ("has_posted", models.BooleanField(default=False)),
                ("message_last_updated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Event Signup Message",
                "verbose_name_plural": "Discord Event Signup Messages",
            },
        ),
        migrations.AddField(
            model_name="discordevent",
            name="signup_message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discord_event",
                to="discordbot.discordeventmsgsignup",
            ),
        ),
    ]
