# Generated by Django 5.2.10 on 2026-03-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordbot", "0003_add_discord_event_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordeventlog",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "System"),
                    (2, "Interaction"),
                    (3, "Signup"),
                    (4, "Notification"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="discordeventlog",
            name="discord_user_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="discordeventlog",
            name="discord_username",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
