# Generated by Django 5.2.10 on 2026-03-29 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0091_tournament_auto_create_hero_drafts_and_more"),
        ("discordbot", "0004_discordeventlog_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordTournamentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("notification", "Notification"),
                            ("system", "System"),
                            ("error", "Error"),
                        ],
                        default="notification",
                        max_length=20,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("draft_link", "Draft Link"),
                            ("herodraft_link", "Hero Draft Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("recipient_count", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_logs",
                        to="app.tournament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Tournament Log",
                "verbose_name_plural": "Discord Tournament Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
