# Generated by Django 5.2.10 on 2026-03-29 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordbot", "0005_discordtournamentlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discordmessagelog",
            name="fired_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who manually fired this task (null = automatic)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fired_discord_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
