# Generated by Django 5.2.10 on 2026-03-29 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordbot", "0006_add_fired_by_to_discordmessagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordeventlog",
            name="message_log",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked outbound message with embed data and Discord API response",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_logs",
                to="discordbot.discordmessagelog",
            ),
        ),
    ]
