# Generated by Django 5.2.10 on 2026-03-29 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordbot", "0007_add_message_log_fk_to_discordeventlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordmessagelog",
            name="tournament_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_logs",
                to="discordbot.discordtournamentlog",
            ),
        ),
    ]
