# Generated by Django 5.2.10 on 2026-05-01 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0008_add_tournament_log_fk_to_messagelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discordmessagelog',
            name='claimed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='discordmessagelog',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='discordmessagelog',
            constraint=models.UniqueConstraint(condition=models.Q(('success__isnull', True), ('success', True), _connector='OR'), fields=('source', 'source_id'), name='uniq_discord_message_log_source_event_when_pending_or_success'),
        ),
    ]
