# Generated by Django 5.2.10 on 2026-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discordbot", "0009_discord_message_log_lease_schema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordtournamentlog",
            name="success",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
