# Generated by Django 5.2 on 2025-04-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_customuser_avatar_alter_customuser_discordid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.TextField(null=True),
        ),
    ]
