# Generated by Django 5.2 on 2025-04-27 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_customuser_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("current_points", models.IntegerField(default=0)),
                (
                    "captain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_captained",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dropin_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teams_dropin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teams_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_played", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("future", "Future"),
                            ("in_progress", "In Progress"),
                            ("past", "Past"),
                        ],
                        default="future",
                        max_length=20,
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(related_name="tournaments", to="app.team"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="tournaments", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "winning_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournaments_won",
                        to="app.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team1",
                        to="app.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_team2",
                        to="app.team",
                    ),
                ),
                (
                    "winning_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_won",
                        to="app.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="app.tournament",
                    ),
                ),
            ],
        ),
    ]
