# Generated by Django 5.2 on 2025-05-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_team_tournament_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="discordNickname",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="guildNickname",
            field=models.TextField(null=True),
        ),
    ]
