# Generated by Django 5.2 on 2025-05-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_customuser_discordnickname_customuser_guildnickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="team1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamesradiant",
                to="app.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="team2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="app.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_games",
                to="app.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="teams",
            field=models.ManyToManyField(related_name="tournament", to="app.team"),
        ),
    ]
