# Generated by Django 5.2 on 2025-05-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_game_team1_alter_game_team2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tournment_type",
            field=models.CharField(
                choices=[
                    ("single_elimination", "Single Elimination"),
                    ("double_elimination", "Double Elimination"),
                    ("swiss", "Swiss Bracket"),
                ],
                default="double_elimination",
                max_length=20,
            ),
        ),
    ]
