# Generated by Django 5.2 on 2025-05-07 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_tournament_tournment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="team1",
        ),
        migrations.RemoveField(
            model_name="game",
            name="team2",
        ),
        migrations.AddField(
            model_name="game",
            name="dire",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamesDire",
                to="app.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="radiant",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamesRadiant",
                to="app.team",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="game",
            name="round",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="game",
            name="users",
            field=models.ManyToManyField(
                related_name="game_stats", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="left_members",
            field=models.ManyToManyField(
                blank=True, related_name="teams_leftzs", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
