# Generated by Django 5.2 on 2025-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_customuser_discordid_alter_customuser_steamid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="position",
        ),
        migrations.AddField(
            model_name="customuser",
            name="positions",
            field=models.JSONField(
                default=dict, help_text="Dota2 positions: 1-5 as keys, bool as value"
            ),
        ),
    ]
