# Generated by Django 5.2 on 2025-07-21 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_game_dire_remove_game_radiant_game_dire_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="left_members",
            field=models.ManyToManyField(
                blank=True, related_name="teams_left", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
