# Generated by Django 5.2 on 2025-07-29 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_alter_team_left_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft",
                        to="app.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftRound",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pick_number",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        help_text="pick number starts at 1, and counts all picks",
                    ),
                ),
                (
                    "pick_phase",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        help_text="pick phase is only increase after all captains have picked once",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DiscordInfo",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="discordId",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="discordNickname",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="discordUsername",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="guildNickname",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="mmr",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nickname",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="positions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Dota2 positions: 1-5 as keys, bool as value",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="steamid",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="dire_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_as_dire",
                to="app.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="gameid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="radiant_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_as_radiant",
                to="app.team",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="app.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="games", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="winning_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games_won",
                to="app.team",
            ),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="assists",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="deaths",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="game",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="app.game",
            ),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="gold_per_minute",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="hero_damage",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="kills",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="tower_damage",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_stats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gamestat",
            name="xp_per_minute",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams_as_captain",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="current_points",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="dropin_members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="teams_as_dropin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="left_members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="teams_as_left",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="teams_as_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="draftround",
            name="captain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_rounds_captained",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="draftround",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draftrounds_choice",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="draftround",
            name="draft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_rounds",
                to="app.draft",
            ),
        ),
        migrations.DeleteModel(
            name="DotaInfo",
        ),
    ]
