# Generated by Django 5.2 on 2025-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_draft_draftround_delete_discordinfo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="captain_order",
            field=models.JSONField(
                default=list, help_text="List of captain pks in draft order"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="draft_order",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Order in which a team picks their players in the draft",
                null=True,
            ),
        ),
    ]
