# Generated by Django 5.2 on 2025-08-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_rename_tournment_type_tournament_tournament_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="captains",
        ),
    ]
