# Generated by Django 5.2 on 2025-08-02 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_remove_tournament_captains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftround",
            name="choice",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draftrounds_choice",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
