# Generated by Django 5.2 on 2025-08-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_draftround_choice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="draft",
            name="captain_order",
        ),
    ]
