# Generated by Django 5.2 on 2025-08-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_remove_draft_captain_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drafts",
                to="app.tournament",
            ),
        ),
    ]
