# Generated by Django 5.2 on 2025-08-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_tournamentmatch_matchslot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournamentmatch",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="tournamentmatch",
            name="winner",
        ),
        migrations.DeleteModel(
            name="MatchSlot",
        ),
        migrations.DeleteModel(
            name="TournamentMatch",
        ),
    ]
