# Generated by Django 5.2 on 2025-09-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_draft_latest_round"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="draft",
            name="latest_round",
        ),
    ]
