# Generated by Django 5.2 on 2025-09-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_auto_20250905_1517"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionsmodel",
            name="carry",
            field=models.IntegerField(
                default=0,
                help_text="Rank of the carry position from 0 (No play) to 5 (best)",
            ),
        ),
        migrations.AddField(
            model_name="positionsmodel",
            name="hard_support",
            field=models.IntegerField(
                default=0,
                help_text="Rank of the hard support position from 0 (No play) to 5 (best)",
            ),
        ),
        migrations.AddField(
            model_name="positionsmodel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="positionsmodel",
            name="mid",
            field=models.IntegerField(
                default=0,
                help_text="Rank of the mid position from 0 (No play) to 5 (best)",
            ),
        ),
        migrations.AddField(
            model_name="positionsmodel",
            name="offlane",
            field=models.IntegerField(
                default=0,
                help_text="Rank of the offlane position from 0 (No play) to 5 (best)",
            ),
        ),
        migrations.AddField(
            model_name="positionsmodel",
            name="soft_support",
            field=models.IntegerField(
                default=0,
                help_text="Rank of the soft support position from 0 (No play) to 5 (best)",
            ),
        ),
    ]
