# Generated by Django 5.2 on 2026-01-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_game_bracket_type_game_next_game_game_next_game_slot_and_more"),
        ("app", "0041_add_bracket_config_fields"),
    ]

    operations = []
