# Generated by Django 5.2 on 2026-01-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_add_bracket_config_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftround",
            name="tie_roll_data",
            field=models.JSONField(
                blank=True,
                help_text="Stores tie resolution: {tied_teams, roll_rounds, winner_id}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="draftround",
            name="was_tie",
            field=models.BooleanField(
                default=False,
                help_text="Whether this round was determined by a tie-breaker roll",
            ),
        ),
    ]
