# Generated by Django 5.2 on 2026-01-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_draftround_tie_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draft",
            name="draft_style",
            field=models.CharField(
                choices=[
                    ("snake", "Snake"),
                    ("normal", "Normal"),
                    ("shuffle", "Shuffle"),
                ],
                default="snake",
                help_text="Draft style: snake, normal, or shuffle",
                max_length=10,
            ),
        ),
    ]
