# Generated by Django 5.2 on 2026-01-07 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_merge_20260107_2239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="draftround",
            name="captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_rounds_captained",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
