# Generated by Django 5.2 on 2026-02-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0077_add_discord_server_id_to_organization"),
        ("league", "0002_populate_league_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="league_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Team members as LeagueUser (for org-scoped MMR)",
                related_name="teams",
                to="league.leagueuser",
            ),
        ),
    ]
