# Generated by Django 5.2 on 2026-02-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0078_team_league_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
