# Generated by Django 5.2.10 on 2026-02-02 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0079_allow_blank_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orglog",
            name="action",
            field=models.CharField(
                choices=[
                    ("add_admin", "Add Admin"),
                    ("remove_admin", "Remove Admin"),
                    ("add_staff", "Add Staff"),
                    ("remove_staff", "Remove Staff"),
                    ("transfer_ownership", "Transfer Ownership"),
                    ("create", "Create Organization"),
                    ("update", "Update Organization"),
                    ("delete", "Delete Organization"),
                    ("approve_claim", "Approve Profile Claim"),
                    ("reject_claim", "Reject Profile Claim"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ProfileClaimRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection (if rejected)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimer",
                    models.ForeignKey(
                        help_text="User requesting to claim the profile (has Discord ID)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization where the target profile is a member",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_requests",
                        to="app.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved/rejected the request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claim_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        help_text="Profile being claimed (has Steam ID, no Discord)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claim_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "-created_at"],
                        name="app_profile_organiz_4b1a91_idx",
                    ),
                    models.Index(
                        fields=["claimer", "status"],
                        name="app_profile_claimer_2ce297_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("claimer", "target_user"),
                        name="unique_pending_claim_request",
                    )
                ],
            },
        ),
    ]
