# Generated by Django 5.2.10 on 2026-02-02 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0081_league_organization_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileclaimrequest",
            name="target_user",
            field=models.ForeignKey(
                help_text="Profile being claimed (has Steam ID, no Discord). NULL after merge.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claim_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
