# Generated by Django 5.2.10 on 2026-02-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0082_alter_profileclaimrequest_target_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaguelog",
            name="action",
            field=models.CharField(
                choices=[
                    ("add_admin", "Add Admin"),
                    ("remove_admin", "Remove Admin"),
                    ("add_staff", "Add Staff"),
                    ("remove_staff", "Remove Staff"),
                    ("add_member", "Add Member"),
                    ("link_organization", "Link Organization"),
                    ("unlink_organization", "Unlink Organization"),
                    ("create", "Create League"),
                    ("update", "Update League"),
                    ("delete", "Delete League"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="orglog",
            name="action",
            field=models.CharField(
                choices=[
                    ("add_admin", "Add Admin"),
                    ("remove_admin", "Remove Admin"),
                    ("add_staff", "Add Staff"),
                    ("remove_staff", "Remove Staff"),
                    ("add_member", "Add Member"),
                    ("transfer_ownership", "Transfer Ownership"),
                    ("create", "Create Organization"),
                    ("update", "Update Organization"),
                    ("delete", "Delete Organization"),
                    ("approve_claim", "Approve Profile Claim"),
                    ("reject_claim", "Reject Profile Claim"),
                ],
                max_length=50,
            ),
        ),
    ]
