# Generated by Django 5.2.10 on 2026-02-08 15:41

from django.db import migrations


def copy_mmr_to_org_user(apps, schema_editor):
    CustomUser = apps.get_model("app", "CustomUser")
    OrgUser = apps.get_model("org", "OrgUser")
    Organization = apps.get_model("app", "Organization")

    try:
        org = Organization.objects.get(pk=1)
    except Organization.DoesNotExist:
        return  # No org with pk=1, nothing to migrate

    users_with_mmr = CustomUser.objects.filter(mmr__isnull=False).exclude(mmr=0)
    for user in users_with_mmr:
        org_user, created = OrgUser.objects.get_or_create(
            user=user,
            organization=org,
            defaults={"mmr": user.mmr},
        )
        if not created and (org_user.mmr is None or org_user.mmr == 0):
            org_user.mmr = user.mmr
            org_user.save(update_fields=["mmr"])


def reverse_noop(apps, schema_editor):
    pass  # Cannot reverse data migration


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0083_alter_leaguelog_action_alter_orglog_action"),
        ("org", "0002_populate_org_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="draftround",
            options={"ordering": ["pick_number"]},
        ),
        migrations.RunPython(copy_mmr_to_org_user, reverse_noop),
        migrations.RemoveField(
            model_name="customuser",
            name="league_mmr",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="mmr",
        ),
    ]
