# Generated by Django 5.2.10 on 2026-02-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0083_alter_leaguelog_action_alter_orglog_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="draftround",
            options={"ordering": ["pick_number"]},
        ),
    ]
