# Generated by Django 5.2.10 on 2026-02-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0084_alter_draftround_options"),
        ("app", "0084_remove_customuser_mmr_fields"),
    ]

    operations = []
