# Generated by Django 5.2.10 on 2026-03-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0086_flip_steamid_steam_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="draft_type",
            field=models.CharField(
                choices=[
                    ("snake", "Snake"),
                    ("normal", "Normal"),
                    ("shuffle", "Shuffle"),
                ],
                default="shuffle",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="game_type",
            field=models.IntegerField(
                choices=[(1, "Dota 2"), (2, "Deadlock")], default=1
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="number_of_teams",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="people_per_team",
            field=models.IntegerField(default=5),
        ),
    ]
