# Generated by Django 5.2.10 on 2026-03-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0087_tournament_draft_type_tournament_game_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="captains_draft_time",
            field=models.IntegerField(
                default=10, help_text="Seconds per draft pick in Captain's Mode"
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="custom_game_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom game/lobby name (for custom game mode)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="game_mode",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("captains_mode", "Captain's Mode"),
                    ("turbo", "Turbo"),
                    ("custom", "Custom Lobby"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="lobby_steam_league_id",
            field=models.IntegerField(
                blank=True,
                help_text="Steam league ID for Dota 2 lobby ticket",
                null=True,
            ),
        ),
    ]
