# Generated by Django 5.2.10 on 2026-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0088_tournament_captains_draft_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="tournament_type",
            field=models.CharField(
                choices=[
                    ("single_elimination", "Single Elimination"),
                    ("double_elimination", "Double Elimination"),
                    ("swiss", "Swiss Bracket"),
                ],
                default="double_elimination",
                max_length=30,
            ),
        ),
    ]
