# Generated by Django 5.2.10 on 2026-03-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0089_alter_tournament_tournament_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orglog",
            name="action",
            field=models.CharField(
                choices=[
                    ("add_admin", "Add Admin"),
                    ("remove_admin", "Remove Admin"),
                    ("add_staff", "Add Staff"),
                    ("remove_staff", "Remove Staff"),
                    ("add_member", "Add Member"),
                    ("transfer_ownership", "Transfer Ownership"),
                    ("create", "Create Organization"),
                    ("update", "Update Organization"),
                    ("delete", "Delete Organization"),
                    ("approve_claim", "Approve Profile Claim"),
                    ("reject_claim", "Reject Profile Claim"),
                    ("set_mmr", "Set MMR"),
                ],
                max_length=50,
            ),
        ),
    ]
