# Generated by Django 5.2.10 on 2026-03-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0090_alter_orglog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="auto_create_hero_drafts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="discord_send_draft_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tournament",
            name="discord_send_herodraft_link",
            field=models.BooleanField(default=False),
        ),
    ]
