# Generated by Django 5.2.10 on 2026-03-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0091_tournament_auto_create_hero_drafts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="discord_send_draft_link",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="discord_send_herodraft_link",
            field=models.BooleanField(default=True),
        ),
    ]
