# Generated by Django 5.2.10 on 2026-04-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0092_draft_dm_defaults_true"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="steam_league_id",
            field=models.IntegerField(
                blank=True,
                db_column="league_id",
                default=None,
                help_text="Steam league ID for match linking",
                null=True,
            ),
        ),
    ]
