# Generated by Django 5.2.10 on 2026-05-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0093_alter_tournament_steam_league_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="league",
            name="steam_league_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
