# Generated by Django 5.2.10 on 2026-05-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_alter_league_steam_league_id'),
        ('user', '0002_backfill_base_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
    ]
