# Generated by Django 5.2.10 on 2026-06-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0095_remove_customuser_avatar_remove_customuser_nickname"),
        # The backfill (user/0004) must run before these columns drop, else
        # the positions/mmr data is lost (T1 ordering lesson).
        ("user", "0004_backfill_game_profiles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="dota_mmr_last_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="has_active_dota_mmr",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="positions",
        ),
    ]
